# Generated by Django 5.2.13 on 2026-05-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_giftboximage"),
    ]

    operations = [
        migrations.AddField(
            model_name="occasion",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="occasions/"),
        ),
    ]
