# Generated by Django 5.2.13 on 2026-05-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_occasion_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftboximage",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
